CREATE TABLE customers (customer_id VARCHAR PRIMARY KEY, signup_at TIMESTAMP NOT NULL, city VARCHAR NOT NULL, acquisition_channel VARCHAR NOT NULL, income_segment VARCHAR NOT NULL, is_subscription_member INTEGER NOT NULL);
CREATE TABLE hubs (hub_id VARCHAR PRIMARY KEY, city VARCHAR NOT NULL, hub_name VARCHAR NOT NULL, capacity_orders_day INTEGER NOT NULL, opened_date DATE NOT NULL);
CREATE TABLE products (product_id VARCHAR PRIMARY KEY, category VARCHAR NOT NULL, product_name VARCHAR NOT NULL, unit_cost DECIMAL(14,2) NOT NULL, list_price DECIMAL(14,2) NOT NULL, is_perishable INTEGER NOT NULL);
CREATE TABLE orders (order_id VARCHAR PRIMARY KEY, customer_id VARCHAR NOT NULL REFERENCES customers(customer_id), hub_id VARCHAR NOT NULL REFERENCES hubs(hub_id), order_at TIMESTAMP NOT NULL, order_status VARCHAR NOT NULL, cancel_reason VARCHAR, item_subtotal DECIMAL(14,2) NOT NULL, discount_amount DECIMAL(14,2) NOT NULL, delivery_fee DECIMAL(14,2) NOT NULL, service_fee DECIMAL(14,2) NOT NULL, gross_amount DECIMAL(14,2) NOT NULL, order_channel VARCHAR NOT NULL);
CREATE TABLE order_items (order_item_id VARCHAR PRIMARY KEY, order_id VARCHAR NOT NULL REFERENCES orders(order_id), product_id VARCHAR NOT NULL REFERENCES products(product_id), quantity INTEGER NOT NULL, unit_price DECIMAL(14,2) NOT NULL, unit_cost DECIMAL(14,2) NOT NULL, is_substituted INTEGER NOT NULL);
CREATE TABLE payments (payment_id VARCHAR PRIMARY KEY, order_id VARCHAR NOT NULL UNIQUE REFERENCES orders(order_id), payment_method VARCHAR NOT NULL, payment_status VARCHAR NOT NULL, paid_amount DECIMAL(14,2) NOT NULL, refund_amount DECIMAL(14,2) NOT NULL, paid_at TIMESTAMP);
CREATE TABLE deliveries (delivery_id VARCHAR PRIMARY KEY, order_id VARCHAR NOT NULL UNIQUE REFERENCES orders(order_id), rider_id VARCHAR NOT NULL, accepted_at TIMESTAMP NOT NULL, promised_at TIMESTAMP NOT NULL, delivered_at TIMESTAMP NOT NULL, distance_km DECIMAL(8,2) NOT NULL, weather_flag INTEGER NOT NULL, delivery_minutes INTEGER NOT NULL, is_late INTEGER NOT NULL);
CREATE TABLE support_tickets (ticket_id VARCHAR PRIMARY KEY, customer_id VARCHAR NOT NULL REFERENCES customers(customer_id), order_id VARCHAR NOT NULL REFERENCES orders(order_id), created_at TIMESTAMP NOT NULL, issue_type VARCHAR NOT NULL, channel VARCHAR NOT NULL, resolution_hours DECIMAL(8,2) NOT NULL, csat_score INTEGER NOT NULL);
CREATE TABLE marketing_exposures (exposure_id VARCHAR PRIMARY KEY, customer_id VARCHAR NOT NULL REFERENCES customers(customer_id), campaign_name VARCHAR NOT NULL, sent_at TIMESTAMP NOT NULL, channel VARCHAR NOT NULL, was_clicked INTEGER NOT NULL, assigned_variant VARCHAR NOT NULL);
